# Generated by Django 4.1 on 2023-09-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0002_user_credentials"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_credentials", name="gender",),
    ]
