# Generated by Django 4.1 on 2023-10-04 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_panel", "0003_remove_user_credentials_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=100)),
                ("apartment_address", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("", "Select a State"),
                            ("ap", "Andhra Pradesh"),
                            ("ar", "Arunachal Pradesh"),
                            ("as", "Assam"),
                            ("br", "Bihar"),
                            ("ch", "Chhattisgarh"),
                            ("ga", "Goa"),
                            ("gj", "Gujarat"),
                            ("hr", "Haryana"),
                            ("hp", "Himachal Pradesh"),
                            ("jh", "Jharkhand"),
                            ("ka", "Karnataka"),
                            ("kl", "Kerala"),
                            ("mp", "Madhya Pradesh"),
                            ("mh", "Maharashtra"),
                            ("mn", "Manipur"),
                            ("ml", "Meghalaya"),
                            ("mz", "Mizoram"),
                            ("nl", "Nagaland"),
                            ("or", "Odisha"),
                            ("pb", "Punjab"),
                            ("rj", "Rajasthan"),
                            ("sk", "Sikkim"),
                            ("tn", "Tamil Nadu"),
                            ("tg", "Telangana"),
                            ("tr", "Tripura"),
                            ("up", "Uttar Pradesh"),
                            ("uk", "Uttarakhand"),
                            ("wb", "West Bengal"),
                            ("an", "Andaman and Nicobar Islands"),
                            ("chd", "Chandigarh"),
                            ("dnh", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("dl", "Delhi"),
                            ("ld", "Lakshadweep"),
                            ("py", "Puducherry"),
                        ],
                        max_length=100,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
                (
                    "address_type",
                    models.CharField(
                        choices=[("B", "Billing"), ("S", "Shipping")], max_length=1
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Addresses",},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("S", "Stripe")], max_length=100),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="razor_pay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="razor_pay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="razor_pay_payment_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_code", models.CharField(blank=True, max_length=20, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("ordered_date", models.DateTimeField()),
                ("ordered", models.BooleanField(default=False)),
                ("being_delivered", models.BooleanField(default=False)),
                ("received", models.BooleanField(default=False)),
                ("refund_requested", models.BooleanField(default=False)),
                ("refund_granted", models.BooleanField(default=False)),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_address",
                        to="user_panel.billingaddress",
                    ),
                ),
                ("items", models.ManyToManyField(to="user_panel.cart")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_panel.payment",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_address",
                        to="user_panel.billingaddress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
