# Generated by Django 4.1 on 2023-10-04 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_panel", "0004_billingaddress_payment_cart_razor_pay_order_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="BillingAddress", new_name="Billing_Address",),
    ]
