# Generated by Django 4.1 on 2023-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_alter_book_description"),
        ("user_panel", "0006_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="admin_panel.book"),
        ),
    ]
