# Generated by Django 4.1 on 2023-10-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0009_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                default=1234,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_panel.address",
            ),
            preserve_default=False,
        ),
    ]
