# Generated by Django 4.1 on 2023-10-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0010_order_billing_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="customer",),
    ]
