# Generated by Django 4.1 on 2023-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0015_order_confirm_remove_cart_razor_pay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("dispatched", "Dispatched"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default=1234,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
