# Generated by Django 4.1 on 2023-10-03 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_book_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
