# Generated by Django 4.1 on 2023-10-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="timestamp", new_name="created_at",
        ),
    ]
