# Generated by Django 4.1 on 2023-10-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_userloginlog"),
    ]

    operations = [
        migrations.DeleteModel(name="UserLoginLog",),
    ]
